[package]
name = "mc-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = "0.5.1"
rocket-include-static-resources = "0.10.5"
zip = "4.0.0"
tokio = { version = "1", features = ["fs", "rt-multi-thread", "macros"] }
async-std = { version = "1", features = ["attributes"] }
